accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


from .views import SignUp

app_name = "accounts"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy("accounts:password_change_done")
        ),
        name="password_change",
    ),
    path(
        "password_change_done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("accounts:password_reset_done")
        ),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("accounts:password_reset_complete")
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("signup/", SignUp.as_view(), name="signup"),
    # path('profile/', UpdateProfile.as_view(), name='profile'),
]

contact/urls.py
from django.contrib import admin
from django.urls import path

from .views import ContactView, SuccessView

app_name = 'contact'

urlpatterns = [
    path('', ContactView.as_view(), name='email-form'),
    path('success/', SuccessView.as_view(), name='success'),
]

posts/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from posts.api.views import PostViewSet, UserViewSet

# Create a router and register viewsets with it.
router = DefaultRouter()
router.register(r"posts", PostViewSet)
router.register(r"users", UserViewSet)

# The API URLs are now determined automatically by the router.
urlpatterns = [path("", include(router.urls))]

posts/urls.py
from django.urls import path
from .views import *

app_name = "posts"

urlpatterns = [
    path("", ListPosts.as_view(), name="index"),
    path("add/", AddPost.as_view(), name="add_post"),
    path("add/drafts/", PostDraftsList.as_view(), name="list_drafts"),
    path("search/", SearchPosts.as_view(), name="search"),
    # post archives
    path("<int:year>/", PostYearArchive.as_view(), name="y_archive"),
    path(
        "<int:year>/<int:month>/",
        PostYearMonthArchive.as_view(month_format="%m"),
        name="ym_archive",
    ),
    path("tag/<str:tag>/", ListByTag.as_view(), name="tag"),
    path("category/<str:name>/", ListByCategory.as_view(), name="category"),
    path("author/<str:author>/", ListByAuthor.as_view(), name="author"),
    path("<slug:slug>/", DetailsPost.as_view(), name="details_post"),
    path("<slug:slug>/delete/", DeletePost.as_view(), name="delete_post"),
    path("<slug:slug>/update/", UpdatePost.as_view(), name="update_post"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        # app_label = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("posts:category", kwargs={"name": self.name})


class Post(models.Model):
    STATUS = (("DRAFT", "Draft"), ("PUBLISHED", "Published"))

    category = models.ManyToManyField(Category, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, unique_for_date="published_date")
    content = MarkdownxField()  # markdownx
    published_date = models.DateTimeField(auto_now=True)
    allow_comments = models.BooleanField(default=True)
    status = models.CharField(default="DRAFT", choices=STATUS, max_length=10)

    # tags mechanism
    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ("-published_date",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:details_post", kwargs={"slug": self.slug})

    @property
    def formatted_markdown(self):
        """
        To properly display markdowned content field
        """
        return markdownify(self.content)

    def is_draft(self):
        return self.status == "DRAFT"

posts/forms.py
from django import forms
from django.utils.text import slugify
from django.utils.crypto import get_random_string
from django.core.exceptions import ValidationError
from .models import Category, Post
from taggit.forms import TagWidget


def make_slug(instance, new_slug=None):
    """Function for creating unique slugs"""

    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    # check if there exists a post with existing slug
    q = Post.objects.filter(slug=slug)
    if q.exists():
        new_slug = "-".join([slug, get_random_string(4, "0123456789")])
        return make_slug(instance, new_slug=new_slug)
    return slug


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ("slug", "author")
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "required": True,
                    "placeholder": "Type your title here...",
                    "class": "form-control",
                }
            ),
            "category": forms.SelectMultiple(
                attrs={"required": True, "class": "form-control"}
            ),
            "status": forms.Select(attrs={"class": "form-control"}),
            "allow_comments": forms.CheckboxInput(attrs={"class": "form-control"}),
            "tags": TagWidget(attrs={"class": "form-control"}),
        }

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        slug = cleaned_data.get("slug")

        if not slug and title:
            cleaned_data["slug"] = slugify(title)

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.slug = make_slug(instance)

        if commit:
            instance.save()
            self.save_m2m()
        return instance

posts/api/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from rest_framework import generics, permissions
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.filters import SearchFilter, OrderingFilter
from .permissions import IsOwnerOrReadOnly
from posts.models import Post
from .serializers import *
from .pagination import *


class PostViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.
    """

    queryset = Post.objects.all()
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly)
    lookup_field = "slug"

    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ["category__name", "author__username", "title", "content"]

    # pagination_class = PostPageNumberPagination # works fine

    def get_serializer_class(self):
        if self.action == "retrieve":
            return PostDetailSerializer
        elif self.action == "create" or self.action == "update":
            return PostCreateUpdateSerializer
        else:
            return PostListSerializer

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

    def perform_update(self, serializer):
        serializer.save(author=self.request.user)


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ["username"]

    pagination_class = UserPageNumberPagination

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from .models import Post, Category
from taggit.models import Tag

from .forms import AddPostForm

# complex lookups (for searching)
from django.db.models import Q

from django.urls import reverse_lazy

# class based views
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView

from django.views import View
from django.utils.decorators import method_decorator

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView

from django.views.generic.dates import YearArchiveView, MonthArchiveView, DayArchiveView

from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
    PermissionRequiredMixin,
)

from django.db import transaction


class CategoryDatesMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        # get queryset of datetime objects for all published posts
        context["dates"] = Post.objects.filter(status="PUBLISHED").datetimes(
            field_name="published_date", kind="month", order="DESC"
        )
        context["recent_posts"] = Post.objects.filter(status="PUBLISHED").order_by(
            "-published_date"
        )[:3]
        return context


class ListPosts(CategoryDatesMixin, ListView):
    model = Post
    template_name = "posts/index.html"
    context_object_name = "posts"
    ordering = ("-published_date",)
    paginate_by = 5


class ListByAuthor(CategoryDatesMixin, ListView):
    model = Post
    context_object_name = "posts"
    template_name = "posts/post_by_author.html"
    paginate_by = 5
    ordering = ("-published_date",)

    def get_queryset(self):
        author = self.kwargs.get("author", None)
        results = []
        if author:
            results = Post.objects.filter(author__username=author)
        return results

    def get_context_data(self, **kwargs):
        """
        Pass author's name to the context
        """
        context = super().get_context_data(**kwargs)
        context["author"] = self.kwargs.get("author", None)
        return context


class ListByTag(CategoryDatesMixin, ListView):
    model = Post
    context_object_name = "posts"
    template_name = "posts/post_by_tag.html"
    paginate_by = 5
    ordering = ("-published_date",)

    def get_queryset(self):
        tag = self.kwargs.get("tag", None)
        results = []
        if tag:
            results = Post.objects.filter(tags__name=tag)
        return results

    def get_context_data(self, **kwargs):
        """
        Pass tag name to the context
        """
        context = super().get_context_data(**kwargs)
        context["tag"] = self.kwargs.get("tag", None)
        return context


class ListByCategory(CategoryDatesMixin, ListView):
    model = Post
    context_object_name = "posts"
    template_name = "posts/post_by_category.html"
    paginate_by = 5
    ordering = ("-published_date",)

    def get_queryset(self):
        category = self.kwargs.get("name", None)
        results = []
        if category:
            results = Post.objects.filter(category__name=category)
        return results

    def get_context_data(self, **kwargs):
        """
        Pass category's name to the context
        """
        context = super().get_context_data(**kwargs)
        context["category"] = self.kwargs.get("name", None)
        return context


class DetailsPost(CategoryDatesMixin, DetailView):
    model = Post
    template_name = "posts/post_detail.html"


# Post archive views
class ArchiveMixin:
    model = Post
    date_field = "published_date"
    allow_future = False
    context_object_name = "posts"


class PostYearArchive(CategoryDatesMixin, ArchiveMixin, YearArchiveView):
    make_object_list = True


class PostYearMonthArchive(CategoryDatesMixin, ArchiveMixin, MonthArchiveView):
    pass


# Create, delete and update post views
class AddPost(
    CategoryDatesMixin, PermissionRequiredMixin, LoginRequiredMixin, CreateView
):
    form_class = AddPostForm
    permission_required = "posts.add_post"
    template_name = "posts/post_form.html"

    # to process request.user in the form
    def form_valid(self, form):
        form.save(commit=False)
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        To use AddPostForm with 'Update' instead of 'Add' text in update view
        """
        context = super().get_context_data(**kwargs)
        context["update"] = False
        return context


class PostDraftsList(
    CategoryDatesMixin, PermissionRequiredMixin, LoginRequiredMixin, ListView
):
    template_name = "posts/list_drafts.html"
    permission_required = "posts.add_post"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.filter(
            status="DRAFT", author__username=self.request.user.username
        )


class DeletePost(
    CategoryDatesMixin, LoginRequiredMixin, UserPassesTestMixin, DeleteView
):
    model = Post
    success_url = reverse_lazy("posts:index")

    def test_func(self):
        """
        Only let the user delete object if they own the object being deleted
        """
        return self.get_object().author.username == self.request.user.username


class UpdatePost(
    CategoryDatesMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView
):
    model = Post
    form_class = AddPostForm

    def test_func(self):
        """
        Only let the user update object if they own the object being updated

        """
        return self.get_object().author.username == self.request.user.username

    def get_context_data(self, **kwargs):
        """
        To use AddPostForm with 'Update' instead of 'Add' text in update view
        """
        context = super().get_context_data(**kwargs)
        context["update"] = True
        return context


class SearchPosts(CategoryDatesMixin, ListView):
    context_object_name = "posts"
    template_name = "posts/post_search.html"
    paginate_by = 5
    ordering = ("-published_date",)

    def get_queryset(self):
        search_query = self.request.GET.get("q", None)
        results = []
        if search_query:
            results = Post.objects.filter(
                Q(category__name__icontains=search_query)
                | Q(author__username__icontains=search_query)
                | Q(title__icontains=search_query)
                | Q(content__icontains=search_query)
            ).distinct()
        return results

posts/templates/base.html
{% load static %}
{% load taggit_templatetags2_tags %}
{% load filters %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Open+Sans|Playfair+Display" rel="stylesheet">

    <title>{% block title %} Django Blog {% endblock %}</title>
</head>

<body>
    <!-- Facebook comments -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.1';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class="container">
        <header class="container mt-4 text-center">
            <a class="h1 text-dark blog-title" href="/">Django Blog</a>           
        </header>

        {% block nav-content %}
        {% if categories %}
        <div class="container my-4">
            <ul class="list-unstyled list-inline text-center h5 font-weight-bold">
            {% for category in categories %}
                <li class="list-inline-item">
                    <a href="{% url 'posts:category' name=category.name %}">{{ category.name }}</a>
                </li>
            {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endblock %}

        {% block editor-panel %}
        <!-- AUTHENTICATED USER WITH PERMISSIONS PANEL -->
        {% if user.is_authenticated and perms.posts.add_post %}
        <!-- it's enough to check permissions for adding posts; 
            changing and deleting is implied
        -->
        <div class="container my-4">
            <hr>
            <ul class="list-unstyled list-inline text-center font-weight-bold">
                <li class="list-inline-item">Editor's Panel:</li>
                <li class="list-inline-item"><a href="{% url 'posts:add_post' %}">New post</a></li>
                <li class="list-inline-item"><a href="{% url 'posts:list_drafts' %}">Your drafts</a></li>
                <li class="list-inline-item"><a href="{% url 'posts:author' author=user.username %}">Your posts</a></li>
            </ul>                           
            <hr>
        </div>
        {% endif %}
        {% endblock %}

        <main class="container">
            <!-- MAIN CONTENT -->
            {% block content %} {% endblock %}
        </main>


        <!-- FOOTER -->
        <footer class="py-3">
            <div class="container">
                {% block footer-content %}
                <div class="row mt-4">
                    <div class="col-md-4">
                        <form method="GET" action="{% url 'posts:search' %}">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search..." name="q">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="button"><i class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                        <p class="mt-4">
                            <i class="fas fa-clock"></i>&nbsp;<b>Recent posts</b>
                            <ul class="list-unstyled mt-2">
                                {% for post in recent_posts %}
                                    <li>
                                        &raquo;&nbsp;<a href="{% url 'posts:details_post' slug=post.slug %}">{{ post }}</a>
                                    </li>
                                {% empty %}
                                    <p>No posts.</p>
                                {% endfor %}
                            </ul>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <i class="fas fa-archive"></i>&nbsp;<b>Archives</b>
                        <ul class="list-unstyled mt-2">
                            {% for date in dates %}
                                <li>
                                    <a href="{% url 'posts:ym_archive' year=date.year month=date.month %}">{{ date.month|month_name }} {{ date.year }}</a>
                                </li>
                            {% empty %}
                                <p>Nothing to display.</p>
                            {% endfor %}
                        </ul>
                        <i class="fas fa-tag"></i><b>Tags</b>
                        <p>
                            {% get_tagcloud as tags %}
                            <ul class="list-unstyled list-inline font-weight-bold mt-2">
                            {% for tag in tags %}
                                <li class="list-inline-item p-1">
                                    <a class="btn btn-sm btn-secondary" href="{% url 'posts:tag' tag=tag %}">{{ tag }}</a>
                                </li>
                            {% endfor %}
                            </ul>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <i class="fas fa-info-circle"></i>&nbsp;<b>About</b>
                        <p>
                            Vestibulum congue risus ornare, dictum nunc ut, venenatis ex. Fusce rhoncus, tellus quis mattis egestas, nunc justo luctus nibh, ultrices auctor orci orci ac ligula.
                        </p>
                        {% if user.is_authenticated %}
                            <div class="text-center">
                                <div class="btn-group btn-group-sm" role="group">
                                    <a href="/" type="button" class="btn btn-success active"><b>{{ user.username.capitalize }}</b> <i class="fas fa-user"></i></button>
                                    <a href="{% url 'accounts:logout' %}?next={{ request.path | urlencode }}" class="btn btn-warning">Logout <i class="fas fa-sign-out-alt"></i></a>
                                </div>
                            </div>
                        {% else %}
                        <div class="text-center">
                            <div class="btn-group btn-group-sm" role="group">
                                <a href="{% url 'accounts:login' %}?next={{ request.path | urlencode }}" class="btn btn-secondary">Sign In <i class="fas fa-sign-in-alt"></i></a>
                                <a href="{% url 'accounts:signup' %}" class="btn btn-outline-secondary">Sign Up <i class="fas fa-user-plus"></i></a>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% endblock %}
                <p class="mt-4 mx-0 text-center text-dark">
                    Copyright &copy; {% now "Y" %} by Author<br>
                    <a href="{% url 'contact:email-form' %}">Contact</a>&nbsp;<a href="{% url 'feed' %}">Subscribe</a><br>
                    <a href="#">Back to top</a>
                </p>
            </div>
        </footer>
    </div>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>