posts/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from posts.api.views import PostViewSet, UserViewSet

# Create a router and register viewsets with it.
router = DefaultRouter()
router.register(r"posts", PostViewSet)
router.register(r"users", UserViewSet)

# The API URLs are now determined automatically by the router.
urlpatterns = [path("", include(router.urls))]

posts/urls.py
from django.urls import path
from .views import *

app_name = "posts"

urlpatterns = [
    path("", ListPosts.as_view(), name="index"),
    path("add/", AddPost.as_view(), name="add_post"),
    path("add/drafts/", PostDraftsList.as_view(), name="list_drafts"),
    path("search/", SearchPosts.as_view(), name="search"),
    # post archives
    path("<int:year>/", PostYearArchive.as_view(), name="y_archive"),
    path(
        "<int:year>/<int:month>/",
        PostYearMonthArchive.as_view(month_format="%m"),
        name="ym_archive",
    ),
    path("tag/<str:tag>/", ListByTag.as_view(), name="tag"),
    path("category/<str:name>/", ListByCategory.as_view(), name="category"),
    path("author/<str:author>/", ListByAuthor.as_view(), name="author"),
    path("<slug:slug>/", DetailsPost.as_view(), name="details_post"),
    path("<slug:slug>/delete/", DeletePost.as_view(), name="delete_post"),
    path("<slug:slug>/update/", UpdatePost.as_view(), name="update_post"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        # app_label = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("posts:category", kwargs={"name": self.name})


class Post(models.Model):
    STATUS = (("DRAFT", "Draft"), ("PUBLISHED", "Published"))

    category = models.ManyToManyField(Category, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, unique_for_date="published_date")
    content = MarkdownxField()  # markdownx
    published_date = models.DateTimeField(auto_now=True)
    allow_comments = models.BooleanField(default=True)
    status = models.CharField(default="DRAFT", choices=STATUS, max_length=10)

    # tags mechanism
    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ("-published_date",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:details_post", kwargs={"slug": self.slug})

    @property
    def formatted_markdown(self):
        """
        To properly display markdowned content field
        """
        return markdownify(self.content)

    def is_draft(self):
        return self.status == "DRAFT"

posts/forms.py
from django import forms
from django.utils.text import slugify
from django.utils.crypto import get_random_string
from django.core.exceptions import ValidationError
from .models import Category, Post
from taggit.forms import TagWidget


def make_slug(instance, new_slug=None):
    """Function for creating unique slugs"""

    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    # check if there exists a post with existing slug
    q = Post.objects.filter(slug=slug)
    if q.exists():
        new_slug = "-".join([slug, get_random_string(4, "0123456789")])
        return make_slug(instance, new_slug=new_slug)
    return slug


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ("slug", "author")
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "required": True,
                    "placeholder": "Type your title here...",
                    "class": "form-control",
                }
            ),
            "category": forms.SelectMultiple(
                attrs={"required": True, "class": "form-control"}
            ),
            "status": forms.Select(attrs={"class": "form-control"}),
            "allow_comments": forms.CheckboxInput(attrs={"class": "form-control"}),
            "tags": TagWidget(attrs={"class": "form-control"}),
        }

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        slug = cleaned_data.get("slug")

        if not slug and title:
            cleaned_data["slug"] = slugify(title)

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.slug = make_slug(instance)

        if commit:
            instance.save()
            self.save_m2m()
        return instance

posts/api/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from rest_framework import generics, permissions
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.filters import SearchFilter, OrderingFilter
from .permissions import IsOwnerOrReadOnly
from posts.models import Post
from .serializers import *
from .pagination import *


class PostViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.
    """

    queryset = Post.objects.all()
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly)
    lookup_field = "slug"

    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ["category__name", "author__username", "title", "content"]

    # pagination_class = PostPageNumberPagination # works fine

    def get_serializer_class(self):
        if self.action == "retrieve":
            return PostDetailSerializer
        elif self.action == "create" or self.action == "update":
            return PostCreateUpdateSerializer
        else:
            return PostListSerializer

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

    def perform_update(self, serializer):
        serializer.save(author=self.request.user)


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ["username"]

    pagination_class = UserPageNumberPagination

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from .models import Post, Category
from taggit.models import Tag

from .forms import AddPostForm

# complex lookups (for searching)
from django.db.models import Q

from django.urls import reverse_lazy

# class based views
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView

from django.views import View
from django.utils.decorators import method_decorator

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView

from django.views.generic.dates import YearArchiveView, MonthArchiveView, DayArchiveView

from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
    PermissionRequiredMixin,
)

from django.db import transaction


class CategoryDatesMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        # get queryset of datetime objects for all published posts
        context["dates"] = Post.objects.filter(status="PUBLISHED").datetimes(
            field_name="published_date", kind="month", order="DESC"
        )
        context["recent_posts"] = Post.objects.filter(status="PUBLISHED").order_by(
            "-published_date"
        )[:3]
        return context


class ListPosts(CategoryDatesMixin, ListView):
    model = Post
    template_name = "posts/index.html"
    context_object_name = "posts"
    ordering = ("-published_date",)
    paginate_by = 5


class ListByAuthor(CategoryDatesMixin, ListView):
    model = Post
    context_object_name = "posts"
    template_name = "posts/post_by_author.html"
    paginate_by = 5
    ordering = ("-published_date",)

    def get_queryset(self):
        author = self.kwargs.get("author", None)
        results = []
        if author:
            results = Post.objects.filter(author__username=author)
        return results

    def get_context_data(self, **kwargs):
        """
        Pass author's name to the context
        """
        context = super().get_context_data(**kwargs)
        context["author"] = self.kwargs.get("author", None)
        return context


class ListByTag(CategoryDatesMixin, ListView):
    model = Post
    context_object_name = "posts"
    template_name = "posts/post_by_tag.html"
    paginate_by = 5
    ordering = ("-published_date",)

    def get_queryset(self):
        tag = self.kwargs.get("tag", None)
        results = []
        if tag:
            results = Post.objects.filter(tags__name=tag)
        return results

    def get_context_data(self, **kwargs):
        """
        Pass tag name to the context
        """
        context = super().get_context_data(**kwargs)
        context["tag"] = self.kwargs.get("tag", None)
        return context


class ListByCategory(CategoryDatesMixin, ListView):
    model = Post
    context_object_name = "posts"
    template_name = "posts/post_by_category.html"
    paginate_by = 5
    ordering = ("-published_date",)

    def get_queryset(self):
        category = self.kwargs.get("name", None)
        results = []
        if category:
            results = Post.objects.filter(category__name=category)
        return results

    def get_context_data(self, **kwargs):
        """
        Pass category's name to the context
        """
        context = super().get_context_data(**kwargs)
        context["category"] = self.kwargs.get("name", None)
        return context


class DetailsPost(CategoryDatesMixin, DetailView):
    model = Post
    template_name = "posts/post_detail.html"


# Post archive views
class ArchiveMixin:
    model = Post
    date_field = "published_date"
    allow_future = False
    context_object_name = "posts"


class PostYearArchive(CategoryDatesMixin, ArchiveMixin, YearArchiveView):
    make_object_list = True


class PostYearMonthArchive(CategoryDatesMixin, ArchiveMixin, MonthArchiveView):
    pass


# Create, delete and update post views
class AddPost(
    CategoryDatesMixin, PermissionRequiredMixin, LoginRequiredMixin, CreateView
):
    form_class = AddPostForm
    permission_required = "posts.add_post"
    template_name = "posts/post_form.html"

    # to process request.user in the form
    def form_valid(self, form):
        form.save(commit=False)
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        To use AddPostForm with 'Update' instead of 'Add' text in update view
        """
        context = super().get_context_data(**kwargs)
        context["update"] = False
        return context


class PostDraftsList(
    CategoryDatesMixin, PermissionRequiredMixin, LoginRequiredMixin, ListView
):
    template_name = "posts/list_drafts.html"
    permission_required = "posts.add_post"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.filter(
            status="DRAFT", author__username=self.request.user.username
        )


class DeletePost(
    CategoryDatesMixin, LoginRequiredMixin, UserPassesTestMixin, DeleteView
):
    model = Post
    success_url = reverse_lazy("posts:index")

    def test_func(self):
        """
        Only let the user delete object if they own the object being deleted
        """
        return self.get_object().author.username == self.request.user.username


class UpdatePost(
    CategoryDatesMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView
):
    model = Post
    form_class = AddPostForm

    def test_func(self):
        """
        Only let the user update object if they own the object being updated

        """
        return self.get_object().author.username == self.request.user.username

    def get_context_data(self, **kwargs):
        """
        To use AddPostForm with 'Update' instead of 'Add' text in update view
        """
        context = super().get_context_data(**kwargs)
        context["update"] = True
        return context


class SearchPosts(CategoryDatesMixin, ListView):
    context_object_name = "posts"
    template_name = "posts/post_search.html"
    paginate_by = 5
    ordering = ("-published_date",)

    def get_queryset(self):
        search_query = self.request.GET.get("q", None)
        results = []
        if search_query:
            results = Post.objects.filter(
                Q(category__name__icontains=search_query)
                | Q(author__username__icontains=search_query)
                | Q(title__icontains=search_query)
                | Q(content__icontains=search_query)
            ).distinct()
        return results

posts/templates/posts/index.html
{% extends 'base.html' %} 

{% load filters %}

{% block title %} Django Blog {% endblock %} 

{% block content %} 

{% for post in posts %} 
{% if not post.is_draft %}
<div class="post">
  <p class="blog-post-title h2">
    <a href="{% url 'posts:details_post' slug=post.slug %}">{{ post.title }}</a>
  </p>
  <div class="row">
    <div class="col-md-6">
      <p>
        Posted on &nbsp;<b>{{ post.published_date|date:"F j, Y" }}</b>&nbsp; by &nbsp;
        <b>
          <a href="{% url 'posts:author' author=post.author.username %}">{{ post.author.username.capitalize }}</a>
        </b>
        |
        <a href="{% url 'posts:details_post' slug=post.slug %}">
          Comments (<span
              class="fb-comments-count"
              data-href="{{ request.build_absolute_uri }}/{{ post.slug }}/"
            ></span>)
        </a>
      </p>
    </div>

    <div class="col-md-6 text-right">
      <b>Categories:</b> &nbsp; 
      {% for category in post.category.all %} 
      {% if not forloop.first %}/ {% endif %}
      <a href="{% url 'posts:category' name=category.name %}">
        {{ category.name }}
      </a>
      {% endfor %}
    </div>
  </div>
  <div class="w-100">
    <!-- shorten + markdown -->
    {{ post.content | shorten_post }}
    <a href="{% url 'posts:details_post' slug=post.slug %}"> Read more</a>
  </div>
</div>
<hr />
{% endif %} 

{% empty %}
<p>No posts.</p>
{% endfor %}
<!-- PAGINATION -->
{% include 'posts/pagination.html' %}

{% endblock %}

posts/templates/posts/list_drafts.html
{% extends 'base.html' %} 

{% block title %} Your drafts {% endblock %} 

{% block content %}
<h3>Your drafts:</h3>
<hr />
{% for post in posts %}
<div class="post">
  <h2>
    <a
      href="{% url 'posts:update_post' slug=post.slug %}"
      class="text-danger"
    >
      {{ post.title }}
    </a>
  </h2>
</div>
<hr />
{% empty %}
<p>No drafts.</p>
{% endfor %}
<!-- PAGINATION -->
{% include 'posts/pagination.html' %}

{% endblock %}

posts/templates/posts/pagination.html
{% if is_paginated %}
    {% load filters %}
    <ul class="pagination justify-content-center">
        {% if page_obj.number == 1 %}
            <li class="page-item disabled">
                <a class="page-link" href="#">First</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?{% url_replace request 'page' 1 %}">First</a>
            </li>
        {% endif %}

        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">&laquo;</a>
            </li>
        {% endif %}

        {% for i in paginator|paginate:page_obj.number %}
            {% if page_obj.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' i %}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">&raquo;</a>
            </li>
        {% endif %}
        {% if page_obj.number == paginator.num_pages %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Last</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?{% url_replace request 'page' paginator.num_pages %}">Last</a>
            </li>
        {% endif %}
    </ul>
{% endif %}

posts/templates/posts/post_archive_month.html
{% extends 'base.html' %}

{% block title %} Posts in {{ month|date:"F Y" }} {% endblock %}

{% block content %}
    <h3>Posts from {{ month|date:"F Y" }}:</h3>
    <hr>
    <!-- Generic post listing template -->
    {% include 'posts/post_list_generic.html' %}
    <!-- PAGINATION -->
    {% include 'posts/pagination.html' %}
{% endblock %}

posts/templates/posts/post_archive_year.html
{% extends 'base.html' %}

{% block title %} Posts in {{ year|date:"Y" }} {% endblock %}

{% block content %}
    <h3>Archived posts in {{ year|date:"Y" }}:</h3>
    <hr>
    <!-- Generic post listing template -->
    {% include 'blog/post_list_generic.html' %}
    <!-- PAGINATION -->
    {% include 'blog/pagination.html' %}
{% endblock %}

posts/templates/posts/post_by_author.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block content %}
    <h3>Posts by {{ author.capitalize }}:</h3>
    <hr>
    <!-- Generic post listing template -->
    {% include 'posts/post_list_generic.html' %}
    <!-- PAGINATION -->
    {% include 'posts/pagination.html' %}
{% endblock %}

posts/templates/posts/post_by_category.html
{% extends 'base.html' %}

{% block title %} Posts in category '{{ category }}' {% endblock %}

{% block content %}
    <h3>Posts in category '{{ category }}':</h3>
    <hr>
    <!-- Generic post listing template -->
    {% include 'posts/post_list_generic.html' %}
    <!-- PAGINATION -->
    {% include 'posts/pagination.html' %}
{% endblock %}

posts/templates/posts/post_by_tag.html
{% extends 'base.html' %}

{% block title %} Posts in tag '{{ tag }}' {% endblock %}

{% block content %}
    <h3>Posts in tag '{{ tag }}':</h3>
    <hr>
    <!-- Generic post listing template -->
    {% include 'posts/post_list_generic.html' %}
    <!-- PAGINATION -->
    {% include 'posts/pagination.html' %}
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Delete Post '{{ object.slug }}'' {% endblock %}


{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %} {{ post.title }} {% endblock %}


{% block content %}
{% if not post.is_draft %}
<div class="post">
    <p class="blog-post-title h2"><a href="{% url 'posts:details_post' slug=post.slug %}">{{ post.title }}</a></p>
    <div class="row">
        <div class="col-md-6">
            <p>
                Posted on &nbsp;<b>{{ post.published_date|date:"F j, Y" }}</b>&nbsp; by &nbsp;<b><a href="{% url 'posts:author' author=post.author.username %}">{{ post.author.username.capitalize }}</a></b>
            </p>
        </div>

        <div class="col-md-6 text-right">
            <b>Categories:</b> &nbsp;
            {% for category in post.category.all %}
                {% if not forloop.first %}/ {% endif %}
                <a href="{% url 'posts:category' name=category.name %}">{{ category.name }}</a>
            {% endfor %}
        </div>
    </div>
    <hr>
    <div class="blog-post">
        {{ post.formatted_markdown|safe }}
    </div>
    <hr>
    <div class="row justify-content-between px-3">
        <div>
            <b>Tags:</b>&nbsp;
            {% for tag_name in post.tags.names %}
                {% if not forloop.first %}, {% endif %}
                <a href="{% url 'posts:tag' tag=tag_name %}">{{ tag_name }}</a>
            {% endfor %}
        </div>

        <div>
            <a href=""><i class="fab fa-twitter px-2"></i></a>
            <a href=""><i class="fab fa-facebook-f px-2"></i></a>
            <a href=""><i class="fab fa-instagram px-2"></i></a>
            <a href=""><i class="fab fa-pinterest px-2"></i></a>
        </div>
        <!-- <div>
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}"><i class="fab fa-facebook-f"></i></a>,
            <a href="https://twitter.com/home?status={{ parsed_content }}%20{{ request.build_absolute_uri }}"><i class="fab fa-twitter"></i></a>,
            <a href="https://plus.google.com/share?url={{ request.build_absolute_uri }}"><i class="fab fa-google-plus-g"></i></a>
        </div> -->

        <!-- Post actions for authenticated users -->
        {% if user.is_authenticated and post.author.username == request.user.username %}
            <div>
                <b>Author actions:</b>&nbsp;
                <!-- Amend post for authenticated author -->
                <a href="{% url 'posts:update_post' slug=post.slug %}">Update</a>
                |
                <!-- Delete post for authenticated author -->
                <a href="{% url 'posts:delete_post' slug=post.slug %}">Delete</a>
            </div>
        {% endif %}     
    </div>
    <hr>
    {% if post.allow_comments == True %}
        <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="3" width="100%"></div>
    {% else %}
        <p><b>Comments are disabled for this post.</b></p>
    {% endif %}
</div>
{% else %}
<p>No such post.</p>
{% endif %}
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}

{% block title %} {% if update %}Update{% else %}Add{% endif %} Post {% endblock %}

{% block content %}
<div class="p-4 text-center m-auto">
    <h3>{% if update %}Update{% else %}Add{% endif %} Post</h3>
    <hr>
    {% if form.errors %}
        {% for error in form.category.errors %}
            <small class="p-1 mb-3 text-center text-white bg-danger">{{ error }}</small>
        {% endfor %}
        {% for error in form.author.errors %}
            <small class="p-1 mb-3 text-center text-white bg-danger">{{ error }}</small>
        {% endfor %}
        {% for error in form.title.errors %}
            <small class="p-1 mb-3 text-center text-white bg-danger">{{ error }}</small>
        {% endfor %}
        {% for error in form.content.errors %}
            <small class="p-1 mb-3 text-center text-white bg-danger">{{ error }}</small>
        {% endfor %}
        {% for error in form.tags.errors %}
            <small class="p-1 mb-3 text-center text-white bg-danger">{{ error }}</small>
        {% endfor %}
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="font-weight-bold">{{ form.title.label_tag }}</label>
                    {{ form.title }} <br>

                    <label class="font-weight-bold">{{ form.category.label_tag }}</label>
                    {{ form.category }}<br>

                    <div class="row">
                        <div class="col-md-6">
                            <label class="font-weight-bold">{{ form.allow_comments.label_tag }}</label>
                            {{ form.allow_comments }}
                        </div>
                        <div class="col-md-6">
                            <label class="font-weight-bold">{{ form.status.label_tag }}</label>
                            {{ form.status }}
                        </div>
                    </div>
                    <div class="mt-4">
                        <label class="font-weight-bold">Comma separated tags:</label>
                        {{ form.tags }}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="font-weight-bold">{{ form.content.label_tag }}</label>
                    {{ form.content }}
                </div>
            </div>
        </div>
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
    {{ form.media }}
</div>
{% endblock %}

posts/templates/posts/post_list_generic.html
{% for post in posts %}
    {% if not post.is_draft %}
        <div class="post">
            <p><a href="{% url 'posts:details_post' slug=post.slug %}"><h2>{{ post.title }}</h2></a></p>
            <div class="row justify-content-between">
                <div class="col-6">
                Posted on &nbsp;<b>{{ post.published_date|date:"F j, Y" }}</b>&nbsp; by &nbsp;<b><a href="{% url 'posts:author' author=post.author.username %}">{{ post.author.username.capitalize }}</a></b>
                |
                <a href="{% url 'posts:details_post' slug=post.slug %}">Comments (<span class="fb-comments-count" data-href="{{ request.build_absolute_uri }}/{{ post.slug }}/"></span>)</a>
                </div>

                <div class="col-6 text-right">
                    <b>Categories:</b> &nbsp;
                    {% for category in post.category.all %}
                        {% if not forloop.first %}/ {% endif %}
                        <a href="{% url 'posts:category' name=category.name %}">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <hr>
    {% endif %}
{% empty %}
    <p>No posts.</p>
{% endfor %}

posts/templates/posts/post_search.html
{% extends 'base.html' %}

{% block title %} Search results for '{{ request.GET.q }}' {% endblock %}

{% block content %}
    {% if request.GET.q %}
        <h3>Search results for '{{ request.GET.q }}':</h3>
        <hr>
        <!-- Generic post listing template -->
        {% include 'posts/post_list_generic.html' %}
        <!-- PAGINATION -->
        {% include 'posts/pagination.html' %}
    {% else %}
        <h3>Search</h3>
        <hr>
        <form method="GET" action="{% url 'posts:search' %}">
            <input type="text" class="form-control" placeholder="Search posts..." name="q">
        </form>
    {% endif %}
{% endblock %}